version: 2.1
jobs:
  docker:
    - image: circleci/ruby:2.5.7-node-browsers-legacy
      environment:
        RAILS_ENV: test
        DB_HOST: 127.0.0.1
    - image: circleci/mysql:5.7
      environment:
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_DATABASE: programming_drill_test
        MYSQL_ALLOW_EMPTY_PASSWORD: true

  working_directory: ~/programming_drill

  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
    - run: gem install bundler:2.0.2
    - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
    - run: bundle exec rails db:create RAILS_ENV=test
    - run: bundle exec rails db:schema:load RAILS_ENV=test
    - run:
        name: RSpec
        command: bundle exec bin/rspec
    - run:
        name: RuboCop
        command: bundle exec rubocop
