version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_HOST: 127.0.0.1
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: password
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: programming_drill_test
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password

    working_directory: ~/programming_drill

    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Selenium のダウンロード
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Selenium の起動
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run: gem install bundler:2.0.2
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load
      - run:
          name: RSpec
          command: bundle exec bin/rspec
      - run:
          name: RuboCop
          command: bundle exec rubocop

      - add_ssh_keys:
          fingerprints:
            - "a2:6d:69:3d:38:c6:f8:3d:ad:54:d0:fd:2a:7d:6a:3c"
