version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_HOST: 127.0.0.1
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: password
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: programming_drill_test
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password

    working_directory: ~/programming_drill

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run: gem install bundler:2.0.2
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load
      - run:
          name: RSpec
          command: bundle exec bin/rspec
      - run:
          name: RuboCop
          command: bundle exec rubocop
